# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfb41861a8a28b617f48cfff3197f58de335a717f6f8797d6bca5b22725d669e4d4af2ca1dddb6a74cefb195809443cacb804b3a278ffaee9e162b89ff5c9ef4

test:
  secret_key_base: fe62569a2838c98dc093de20c519d03e65228ea9f76a90aec95ad80ef3aea162c84184eaa28433ec6cce2effb8a90a880dcc25729952f8387ca5709fd39d4b88

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
